### ISSUE TITLE
USER STORY Hiding poll identity

### ISSUE THREAD

**Issue by olliesharp5** [olliesharp5/love-running#3]
In order to automatically hide the poll as an administrator, I can pick the expiry date while publishing the poll.

### **Acceptance Criteria:**
1. The poll should disappear at 11:59 PM on the target date
2. The real estate of the "Poll" should be reversed on the home page. A message that reads "Stay tuned, a new poll is coming soon" should appear if no other poll is active.
3. The administrator expiry date should be at least 3 days after the current date. 

### **Tasks**
- [ ] Update the admin module view: the poll design (HTML, CSS) to include date picker.
- [ ] Update the website view: show "Stay tuned a new poll is coming soon.
- [ ] Create a JavaScript function to validate the expiry date is at least after 3 days 
- [ ] Create a job to check expired Polls everyday at 11:59 PM and hide them. 
- [ ] Update the controller function
- [ ] Update unit test scripts 
- [ ] Test functionality
